markdown: kramdown
permalink: /writing/:year/:month/:day/:title
baseurl: /
baseurl_resume: /cv/
baseurl_papers: /art/pdfs
title: Owen Martin live on the internet
name: Owen Martin
tel: +1 3033256880
email: martin.owen22@gmail.com
website: owen-martin
github: owingit
github_full: www.github.com/owingit
twitter: lepurplemartin
instagram: lepurplemartin

collections:
  posts:
  photo_gallery:
  pendulum_gallery:
