markdown: kramdown
permalink: /blog/:year/:month/:day/:title


baseurl: /
baseurl_resume: /cv/
title: Personal Website and Blog
name: Owen Martin
tel: +1 3033256880
email: martin.owen22@gmail.com
website: owingit.github.io
github: www.github.com/owingit
twitter: lepurplemartin

