markdown: kramdown
permalink: /cv/:title


baseurl: /cv/
title: Resume
name: Owen Martin
tel: +1 3033256880
email: martin.owen22@gmail.com
website: owingit.github.io
github: www.github.com/owingit
twitter: "@lepurplemartin"
